### ISSUE TITLE
Try to use a proper copyright symbol

### ISSUE THREAD

**Issue by eatpro** [softwaremom00/teacozy#1]
https://github.com/softwaremom00/teacozy/blob/998a3afb364834a7d82e8367b75a23694e2f9b26/index.html#L100

Using the actual copyright symbol ```Ⓒ``` is the best practices approach to indicating copyright and for a real website which would be used by the public, it would of legal signifficance so you should always use it. This can easily be done by using the html escape code:
```&copy;```

**Comment by softwaremom00** [comment]
Thanks.  Sounds good.
