### ISSUE TITLE
Always use "backup" fonts when possible

### ISSUE THREAD

**Issue by eatpro** [softwaremom00/teacozy#2]
https://github.com/softwaremom00/teacozy/blob/998a3afb364834a7d82e8367b75a23694e2f9b26/resources/css/style.css#L3

Sometimes things go wrong and a font can't load properly or in some cases the user simply doesn't have that font, for this reason it is a best practice to have "backup" fonts. For example:
```font-family: Helvetica, sans-serif;```

**Comment by softwaremom00** [comment]
Thank you.  I should have included that one as well.
