### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by eatpro** [softwaremom00/teacozy#3]
### Criteria 1: HTML Structure  
* _Score Level:_ 4 (Exceeds Expectations)
* _Comment(s):_ Structure looks great and even has comments about each section
 
### Criteria 2: Visual Layout
* _Score Level:_ 4
* _Comment(s):_ Visual layout is perfect and within spec
 
### Criteria 3: Use of Flexbox
* _Score Level:_ 4
* _Comment(s):_ Flexbox used and works properly
 
### Criteria 4: Implementation of Design Specification and Content
* _Score Level:_ 3 (Meets Expectations)
* _Comment(s):_ All content is there and in spec, the css more repetitive than it could be but this is a small detail.
 
### Overall Score: 15/16
Overall good job! The site looks good and is in spec while using many best practices! My main words of advice would be to try and make your CSS a bit more DRY as I saw a bit of unnecessary repetition. Also, while not a huge deal, in general class and id names should use the convention of lowercase words and hyphens like-this. Keep it up and happy coding!

**Comment by softwaremom00** [comment]
Thank you.
